# placeholder file - it's not used at the moment but will be soon!

chord_weights:
  minor: 0.5
  major: 0.5
  dim: 0
MajorForms:
  - C
  - A
  - G
  - E
  - D
MinorForms:
  - A
  - E
  - D

delay_between_tries:
  chords: 5